{{- if and .Values.database.enabled .Values.database.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manifimind-crm.fullname" . }}-database-pvc
  labels:
    {{- include "manifimind-crm.labels" . | nindent 4 }}
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.database.persistence.storageClass }}
  storageClassName: {{ .Values.database.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- end }}
